### ISSUE TITLE
Create Fallback Presentations

### ISSUE THREAD

**Issue by ghost** [Utah-Node-Ninjas/unn-committee#12]
When we don't have presenters, it would be great to have presentations topics ready and waiting.  This would be a great opportunity for us to research topics of interest.  Thoughts?

**Comment by ghost** [comment]
@joeycozza and @ryanswapp , what are your thoughts on this one?  Should we each create one, anticipating gaps in the future?

**Comment by ryanswapp** [comment]
I'm always happy to present. The problem is that I rarely have the time to come up with a good presentation so I think creating a fallback presentation would be a good idea. I'll think of something I'd like to present on and put together a presentation.

**Comment by ghost** [comment]
I'm closing old issues that are no longer relevant.
