### ISSUE TITLE
Bi-weekly?

### ISSUE THREAD

**Issue by ghost** [Utah-Node-Ninjas/unn-committee#16]
@joeycozza & @ryanswapp ,

What are your thoughts on dropping down to bi-weekly meetups in Provo?  

Here is my reasoning:
1. We've started a slc chapter, we would still have weekly meetups, but each month, two would be in SLC and two in Provo
2. Takes a little pressure off us organizers, and let's us focus on higher quality and consistent presentations.
3. Upgrade to better pizza or different food in Provo
4. I recently received this note:

> We'll be welcoming the Google Developer Group to the Startup Dojo as another fellow user group and they will be coming on one Wednesday of the month. I'm still determining exactly which Wednesday   each month that will be, but it does mean that you're team will need to meet in the conference room adjacent to the larger room you're normally in, as the GDG has about 30-40 members.

I do like the idea of a weekly, informal gathering, but I question if it is sustainable.  If we go bi-weekly, we can avoid colliding with GDG.  If we stuck to weekly, we would need to make sure hack night is the same night as GDG.

Month:
week 1: SLC NodeSchool & Hack Night
week 2: Provo NodeSchool & Hack Night
week 3: SLC Presentations
week 4: Provo Presentations

**Comment by joeycozza** [comment]
I had this thought recently, and I think bi-weekly is much more sustainable, and is the way to go.

**Comment by ryanswapp** [comment]
Sure, that would work for me. When would you like to implement the change?

**Comment by ghost** [comment]
We have presenters through March 18th.  I will tentatively set that date as the cutoff where we switch to bi-weekly in Provo.  I still need to get the schedule for the GDG meetup, and will reschedule the days based on that.

**Comment by ghost** [comment]
Ok, I spoke with our Provo venue, and the GDG meetup will be the last Wednesday of each month.  I said we would take the first and third Wednesdays of the month.

I will go ahead and change the schedule on meetup.com, starting March 4th and reschedule the march 18th presenter

For a more seamless transition:
1st Wednesday of month: Provo - Presentations
2nd Wednesday of month: SLC - Presentations
3rd Wednesday of month: Provo - Nodeschool
4th Wednesday of month: SLC - Nodeschool
