### ISSUE TITLE
Coding Campus Project

### ISSUE THREAD

**Issue by ghost** [Utah-Node-Ninjas/unn-committee#17]
@joeycozza & @ryanswapp ,

We have an offer from coding campus for free development work on a two week project.

My idea is to allow Nodeschoolers to register with us.  A server job would track their progress by running the nodeschool validation on projects committed to their git repo.  They would graduate as a "Node Ninja" when all the nodeschool workshoppers were completed.  

We can work out the details of the requirements if you both think it is a good idea.  Throw in your own ideas if you have any.

**Comment by ryanswapp** [comment]
That's interesting.. So they are just going to set aside two weeks to build
something for us? Cool. I like your idea. Maybe they could add a bit more
gamification too? It could also be like a mini stackoverflow but only for
node. People could get points for answering questions if their answers are
good.

**Comment by ghost** [comment]
Yes, I like the gamification idea.  

We could rank based on level of completion of nodeschool workshoppers, go through the different color martial arts belts based on % completed.

I wouldn't want to reproduce stackoverflow functionality, but it would be cool if we could use stackoverflow's api and pull info on any questions/answers with node.js tags.  We might also pull info from NPM on the number of packages they have created.

**Comment by ghost** [comment]
We should probably make it more generic, so any nodeschool could use it.

**Comment by Sburdge** [comment]
Hey guys, I was able to talk with the team today and they actually had already found another project :/ We'll keep you in mind for upcoming projects though!

**Comment by ghost** [comment]
No problem, thanks for letting us know.

**Comment by ghost** [comment]
I'm closing old issues that are no longer relevant.
