### ISSUE TITLE
Lightning talks on node-school/hack nights

### ISSUE THREAD

**Issue by ghost** [Utah-Node-Ninjas/unn-committee#21]
@ryanswapp & @joeycozza 
A member suggested we only do presentations.  After more discussion, it seemed that if we had lightning talks on the hack nights, we might add more value and encourage more knowledge sharing than possible on formal presentation nights.

I do like the informal nights, and wouldn't want to eliminate them altogether, but I do see the need to add more structure and value.

Proposal:
Start our hack nights with  four 5 minute lightning talks. Everyone is welcome to present.  I would think that if it is even setting up your favorite IDE with some node support, or anything remotely related, we encourage the average member to share what they have learned.  

Thoughts?

**Comment by ryanswapp** [comment]
Yes, I agree that it would be nice to have more presentations. I think the problem is finding presenters right? Or do you think we'd have a steady supply of them?

Also, I'm not sure 5 minute talks would be long enough to present something useful. Maybe though? What about two 10-15 minutes talks?

**Comment by ghost** [comment]
Ok, 10min, no issue if you go over.  Yes, presenters are in short supply at the moment, but I plan to reach out more, hitting other meetups is helpful.

For hack night we might encourage people to pick something they recently learned or could research...for example I want to get better at debugging, I might present how to do it at command line and setup in webstorm.

**Comment by ghost** [comment]
Or, should we focus solely on presentations?  Do you find the nodeschool/hack-nights helpful?  Should send out a survey on meetup site?

**Comment by ghost** [comment]
Sorry for the chatter, as you can tell, I'm giving this a lot of thought.

We have nodeschool chapters for Provo and SLC, so we need to fulfill that responsibility. I also feel strongly in support of the nodeschool concept, both teaching beginners and encouraging mastery with hands-on lessons, not just passively watching presentations.

I vote for the following:  one nodeschool night and one presentation night.  We would drop "hack night" and keep focused on completing nodeschool workshoppers (which includes getting newbies up and running).  Those who prefer presentations just come on that night. 

@ryanswapp , as you mentioned, presenters are in short supply and I think we'll benefit from just focusing on one action packed night of presentations and lightning talks.  For the months we have presenters beating down our door, we could schedule another night of presentations.

**Comment by ghost** [comment]
I'm closing old issues that are no longer relevant.
