### ISSUE TITLE
Rebrand to Utah Node.js

### ISSUE THREAD

**Issue by ghost** [Utah-Node-Ninjas/unn-committee#22]
I think it is time for Utah Node.js Ninjas to rebrand to Utah Node.js.  In addition to the convenience of being shorter, I think a short, professional branding will appeal to a wider audience.

Please let us know your thoughts.

**Comment by josep2** [comment]
I agree on the rebranding. I never like the title "Ninjas" in general. It implies took much focus on hacker culture rather than engineering culture.

**Comment by creayt** [comment]
Please do, it's a big improvement. You may not even need the ".js".

**Comment by britton-jb** [comment]
Yeah it's time for a rebrand. I'm with @creayt, we don't even need .js

**Comment by ryanswapp** [comment]
I have no objection to the rebrand. It does sound more professional. However, I disagree with @creayt and @britton-jb in dropping the .js. Node.js is the official name of the platform and only those familiar with it refer to it as Node. In addition, Node is a fairly common word among many industries and thus I think it is important to keep the .js in order for it to be clearly differentiated.

**Comment by josep2** [comment]
I agree with @ryanray. Node is too common of a word Node.js is the official name of the platform.

**Comment by barbaraliau** [comment]
Agree with @ryanswapp and @josep2

**Comment by spencerlambert** [comment]
Dropping the term Ninja loses some warmth and approachability.   "Utah Node.js" is a bit factual and bland for me.   You could for sure drop the Utah, just Node Ninjas, or Node Brains if you wanted to be less hacky (I personally like the ninja).  But it definitely needs something more that just Utah Node.js.

**Comment by ryanray** [comment]
:+1: to Utah Node.js - I don't like Ninjas - I don't mind the idea of warmth and approachability but there has to be a better way to achieve that. I cringe when I see a job posting or any other text that refers to "ninjas" or "rockstars".

**Comment by luishrd** [comment]
I agree

**Comment by coolaj86** [comment]
I propose [Brogrammatic Ninja-throwing Rockstar Badassian Wizards](https://gist.github.com/coolaj86/9256619) or "Nodesters" for short.

**Comment by ghost** [comment]
@spencerlambert I hear what you are saying about losing the warmth, but I do want to fly a mainstream banner.  How about we have events geared toward beginners, and we can call the event whatever we want.

In regard to Node vs Node.js.  I've already ran into issues communicating with other people who haven't heard of Node.js, with only Node.  So I would agree that Node.js is more practical.

@coolaj86 Oh, behave.

**Comment by ghost** [comment]
We are going to run with "Utah Node.js".  Next up, submit your logo's here: #23
