### ISSUE TITLE
Utah Node.js Logo

### ISSUE THREAD

**Issue by ghost** [Utah-Node-Ninjas/unn-committee#23]
Assuming we rebrand to Utah Node.js #22 , please submit proposals for new logos here.

We should wait on the outcome of Node's official logo update until we make the final decision:  https://github.com/nodejs/evangelism/issues/179

**Comment by ghost** [comment]
Here is the one @chipe13 submitted.  He said he can clean up the edges for us.

![image](https://cloud.githubusercontent.com/assets/546259/10853512/0cbf393e-7efc-11e5-8d19-54a3ab1a947f.png)

**Comment by josep2** [comment]
![utahjslogo](https://cloud.githubusercontent.com/assets/1683949/10869979/783ca238-807c-11e5-99dd-b38368bcf2dc.jpg)

**Comment by josep2** [comment]
Beehive state!

**Comment by ghost** [comment]
@josep2 Thank you for your submission.  I do like the tie in with the beehive state.  We decided to just run with the first one.  We'll have another opportunity to update the logo when the official one gets updated.

**Comment by ghost** [comment]
@josep2 This logo made me think of your submission: https://pbs.twimg.com/profile_images/378800000289155487/0b834a3a1259af3bd36539db0e8d4a52.png

**Comment by josep2** [comment]
Similar indeed.
